#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

#readonly DEB_RELEASE="unstable"
readonly BASE_TARGET_DIR="base"
readonly KDIR="../linux"
#readonly DEB_MIRROR="http://ftp.us.debian.org/debian/ "
#readonly PACKAGES=(
#  "openssh-server"
#  "vim"
#  "sudo"
#  "less"
#  "curl"
#  "iproute2"
#  "iptables"
#  "bridge-utils"
#  "telnet"
#  "clang"
#  "git"
#  "bc"
#  "libelf-dev"
#  "libdw-dev"
#  "ninja-build"
#  "build-essential"
#)

mkdir -p "${BASE_TARGET_DIR}/nix" inst
! [[ -f ./latest-iso-minimal-x86_64-linux ]] && wget http://nixos.org/releases/nixos/latest-iso-minimal-x86_64-linux
modprobe loop
mount -o loop latest-iso-minimal-x86_64-linux inst
unsquashfs -d ${BASE_TARGET_DIR}/nix/store inst/nix-store.squashfs '*'

cd ${BASE_TARGET_DIR}

INIT=$(find . -type f -path '*nixos*/init' | sed 's|./||')
BASH=$(find . -type f -path '*/bin/bash' | tail -n 1 | sed 's|./||')

exit

sed -i "s,exec systemd,exec /$BASH," $INIT

chroot . /$INIT


exit

# Make root passwordless for convenience.
sudo sed -i '/^root/ { s/:x:/::/ }' "${BASE_TARGET_DIR}/etc/passwd"
# Add a getty on the virtio console
#echo 'V0:23:respawn:/sbin/getty 115200 hvc0' | sudo tee -a "${BASE_TARGET_DIR}/etc/inittab"
# Automatically bring up enp0s4 using DHCP
#printf '\nsource-directory /etc/network/interfaces.d\n\nauto enp0s4\niface enp0s4 inet dhcp\n' | sudo tee "${BASE_TARGET_DIR}/etc/network/interfaces"
# Set up my ssh pubkey for root in the VM
sudo mkdir -p "${BASE_TARGET_DIR}/root/.ssh/"
cat ~/.ssh/id_?sa.pub | sudo tee "${BASE_TARGET_DIR}"/root/.ssh/authorized_keys
# Add our units and helper scripts
sudo cp img/bin/* "${BASE_TARGET_DIR}/usr/local/bin"
for unit in $(ls img/units/); do
  sudo cp "img/units/$unit" "${BASE_TARGET_DIR}/etc/systemd/system"
  sudo chroot "${BASE_TARGET_DIR}" /bin/bash -c "systemctl enable $unit"
done

# kernel modules
sudo rm -rf "${BASE_TARGET_DIR}/lib/modules"
sudo make -C "${KDIR}" INSTALL_MOD_PATH="${PWD}/${BASE_TARGET_DIR}" modules_install
sudo make -C "${KDIR}" INSTALL_HDR_PATH="${PWD}/${BASE_TARGET_DIR}/usr" headers_install

dd if=/dev/zero of="${BASE_TARGET_DIR}.img" bs=1M seek=4095 count=1
mkfs.ext4 -F "${BASE_TARGET_DIR}.img"
sudo mkdir -p "/mnt/${BASE_TARGET_DIR}"
sudo mount -o loop "${BASE_TARGET_DIR}.img" "/mnt/${BASE_TARGET_DIR}"
sudo cp -a "${BASE_TARGET_DIR}/." "/mnt/${BASE_TARGET_DIR}/."
sudo umount "/mnt/${BASE_TARGET_DIR}"
