#! /bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

function util::join() {
  local IFS="$1"
  shift
  echo "$*"
}

readonly DEB_RELEASE="unstable"
readonly BASE_TARGET_DIR="base"
readonly KDIR="../linux"
readonly DEB_MIRROR="http://ftp.us.debian.org/debian/ "
readonly PACKAGES=(
  "openssh-server"
  "vim"
  "sudo"
  "less"
  "curl"
  "iproute2"
  "iptables"
  "bridge-utils"
  "telnet"
  "git"
  "bc"
  "libelf-dev"
  "libdw-dev"
  "ninja-build"
  "build-essential"
  "bison"
  "cmake"
  "flex"
  "libedit-dev"
  "libllvm3.7"
  "llvm-3.7-dev"
  "libclang-3.7-dev"
  "python"
  "zlib1g-dev"
)

mkdir -p "${BASE_TARGET_DIR}"
sudo debootstrap --verbose --include=$(util::join "," "${PACKAGES[@]}") "${DEB_RELEASE}" "${BASE_TARGET_DIR}/" "${DEB_MIRROR}"

# debootstrap isn't cleaning up
sudo umount /home/mikedanese/lkdev/base/proc/sys/fs/binfmt_misc || :
sudo umount /home/mikedanese/lkdev/base/proc || :


# Make root passwordless for convenience.
sudo sed -i '/^root/ { s/:x:/::/ }' "${BASE_TARGET_DIR}/etc/passwd"
# Add a getty on the virtio console
echo 'V0:23:respawn:/sbin/getty 115200 hvc0' | sudo tee -a "${BASE_TARGET_DIR}/etc/inittab"
# Automatically bring up enp0s4 using DHCP
printf '\nsource-directory /etc/network/interfaces.d\n\nauto enp0s4\niface enp0s4 inet dhcp\n' | sudo tee "${BASE_TARGET_DIR}/etc/network/interfaces"
# Set up my ssh pubkey for root in the VM
sudo mkdir -p "${BASE_TARGET_DIR}/root/.ssh/"
cat ~/.ssh/id_?sa.pub | sudo tee "${BASE_TARGET_DIR}"/root/.ssh/authorized_keys
# Add our units and helper scripts
sudo cp img/bin/* "${BASE_TARGET_DIR}/usr/local/bin"
for unit in $(ls img/units/); do
  sudo cp "img/units/$unit" "${BASE_TARGET_DIR}/etc/systemd/system"
  sudo chroot "${BASE_TARGET_DIR}" /bin/bash -c "systemctl enable $unit"
done

# kernel modules
sudo rm -rf "${BASE_TARGET_DIR}/lib/modules"
sudo make -C "${KDIR}" INSTALL_MOD_PATH="${PWD}/${BASE_TARGET_DIR}" modules_install
sudo make -C "${KDIR}" INSTALL_HDR_PATH="${PWD}/${BASE_TARGET_DIR}/usr" headers_install

sudo qemu-nbd -c /dev/nbd0 base.qcow2
yes | sudo mkfs.ext4 /dev/nbd0

sudo mkdir -p "/mnt/${BASE_TARGET_DIR}"
sudo mount /dev/nbd0 "/mnt/${BASE_TARGET_DIR}"

sudo cp -a "${BASE_TARGET_DIR}/." "/mnt/${BASE_TARGET_DIR}/."

exit 100

sudo umount "/mnt/${BASE_TARGET_DIR}"
sudo qemu-nbd -d /dev/nbd0
