#! /bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

function util::join() {
  local IFS="$1"
  shift
  echo "$*"
}

readonly DEB_RELEASE="jessie"
readonly DEB_MIRROR="http://ftp.us.debian.org/debian/ "
readonly PACKAGES=(
  "openssh-server"
  "vim"
  "sudo"
  "less"
  "curl"
  "iproute2"
  "iptables"
  "bridge-utils"
  "telnet"
)

# Build a Wheezy chroot. Install an sshd, since it will be handy
# later.
sudo rm -rf "${DEB_RELEASE}"
mkdir "${DEB_RELEASE}"
sudo debootstrap --verbose --include=$(util::join "," "${PACKAGES[@]}") "${DEB_RELEASE}" "${DEB_RELEASE}/" "${DEB_MIRROR}"

# Perform some manual cleanup on the resulting chroot:

# Make root passwordless for convenience.
sudo sed -i '/^root/ { s/:x:/::/ }' "${DEB_RELEASE}/etc/passwd"
# Add a getty on the virtio console
echo 'V0:23:respawn:/sbin/getty 115200 hvc0' | sudo tee -a "${DEB_RELEASE}/etc/inittab"
# Automatically bring up eth0 using DHCP
printf '\nauto eth0\niface eth0 inet dhcp\n' | sudo tee -a "${DEB_RELEASE}/etc/network/interfaces"
# Set up my ssh pubkey for root in the VM
sudo mkdir "${DEB_RELEASE}/root/.ssh/"
cat ~/.ssh/id_?sa.pub | sudo tee "${DEB_RELEASE}"/root/.ssh/authorized_keys

# Build a disk image
dd if=/dev/zero of="${DEB_RELEASE}.img" bs=1M seek=4095 count=1
mkfs.ext4 -F "${DEB_RELEASE}.img"
sudo mkdir -p "/mnt/${DEB_RELEASE}"
sudo mount -o loop "${DEB_RELEASE}.img" "/mnt/${DEB_RELEASE}"
sudo cp -a "${DEB_RELEASE}/." "/mnt/${DEB_RELEASE}/."
sudo umount "/mnt/${DEB_RELEASE}"
