#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

ROOT_DIR=".tmp/initfs"
rm -rf "${ROOT_DIR}"

mkdir -p "${ROOT_DIR}"/{bin,dev,etc,lib,lib64,mnt/root,proc,root,sbin,sys,opt}
cp -a /bin/busybox "${ROOT_DIR}/bin"

for tarball in modules.tar headers.tar base.tar; do
  cp ".tmp/${tarball}" "${ROOT_DIR}/opt"
done


busybox_commands="$(busybox --list)"

pushd "${ROOT_DIR}"/bin

for bin in $busybox_commands; do
  ln -s -f busybox $bin
done;

popd

cp init.sh "${ROOT_DIR}/init"

pushd "${ROOT_DIR}/"
find . -print0 | cpio --null -ov --format=newc | gzip -9 > ../initramfs.cpio.gz
popd
