#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_DIR="target"
readonly KDIR="../linux"
mkdir -p "${TARGET_DIR}/nix" inst
! [[ -f ./latest-iso-minimal-x86_64-linux ]] && wget http://nixos.org/releases/nixos/latest-iso-minimal-x86_64-linux

modprobe loop
mount -o loop latest-iso-minimal-x86_64-linux inst
unsquashfs -d ${TARGET_DIR}/nix/store inst/nix-store.squashfs '*'

cd ${TARGET_DIR}

INIT=$(find . -type f -path '*nixos*/init' | sed 's|./||')
BASH=$(find . -type f -path '*/bin/bash' | tail -n 1 | sed 's|./||')

# need to create nix kernel package and put shit in appropriate place, not sure if chroot is actually necessary 
# unless we want to run a nix install

sudo make -C "${KDIR}" INSTALL_MOD_PATH="${PWD}/${TARGET_DIR}" modules_install
sudo make -C "${KDIR}" INSTALL_HDR_PATH="${PWD}/${TARGET_DIR}/usr" headers_install

dd if=/dev/zero of="${BASE_TARGET_DIR}.img" bs=1M seek=4095 count=1
mkfs.ext4 -F "${BASE_TARGET_DIR}.img"
sudo mkdir -p "/mnt/${BASE_TARGET_DIR}"
sudo mount -o loop "${BASE_TARGET_DIR}.img" "/mnt/${BASE_TARGET_DIR}"
sudo cp -a "${BASE_TARGET_DIR}/." "/mnt/${BASE_TARGET_DIR}/."
sudo umount "/mnt/${BASE_TARGET_DIR}"
