#!/bin/busybox sh

set -o errexit
set -o nounset
set -o pipefail
set -x

rescue_shell() {
  echo "Something went wrong. Dropping to a shell."
  exec sh
}

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -o rw /dev/sda1 /mnt/root || rescue_shell

IGNITION_LABEL="LABEL=\"ignition\""

if blkid | grep -q "${IGNITION_LABEL}"; then
  mount --bind /proc /mnt/root/proc
  mount --bind /sys  /mnt/root/sys
  mount --bind /dev  /mnt/root/dev

  mkdir -p /run
  mkdir -p /mnt/root/var/lib/ignition
  mount --bind /run /mnt/root/var/lib/ignition
  mkdir -p /usr/share/oem
  device="$(blkid | grep "${IGNITION_LABEL}" | awk -F':' '{print $1}')"
  mount -t auto "${device}" /usr/share/oem

  ignition --stage files --oem pxe --root /mnt/root
  chroot /mnt/root systemctl preset-all || rescue_shell

  umount /mnt/root/proc
  umount /mnt/root/sys
  umount /mnt/root/dev
  umount /usr/share/oem
  umount /mnt/root/var/lib/ignition

fi

umount /proc
umount /sys

sed -i '/^root/ { s/:x:/::/ }' "/mnt/root/etc/passwd"

chroot /mnt/root/ chmod 755 /

exec switch_root /mnt/root /sbin/init
