#!/bin/bash

sysctl net.ipv4.ip_forward=1

ip link add virbr0 type bridge
ip addr add 172.18.0.2/16 dev virbr0
ip link set virbr0 up

dnsmasq --interface=virbr0 --bind-interfaces --dhcp-range=172.18.0.2,172.18.255.254

iptables -t nat -A POSTROUTING -o ens33 -j MASQUERADE
